---

- name: Set dotfiles folder destination
  set_fact:
    dotfiles_dest: "/home/{{ user.name }}/{{ dotfiles.destination }}"

- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles.url }}"
    dest: "{{ dotfiles_dest }}"
    accept_hostkey: yes
    update: yes
    force: yes

- name: Install dotfiles (requires rcm)
  command: "rcup -d {{ dotfiles_dest }}"
  when: dotfiles.installation == 'true'
  become: yes
  become_user: "{{ user.name }}"
