---

- name: Set dotfiles folder destination
  set_fact:
    dotfiles_dest: "/home/{{ user.name }}/{{ dotfiles.destination }}"

- name: Install rcm
  aur:
    name: rcm
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: dotfiles.installation == 'true'
  tags:
    - aur

- name: Close dotfiles repository
  git:
    repo: "{{ dotfiles.url }}"
    dest: "{{ dotfiles_dest }}"
    accept_hostkey: yes
    update: yes
    force: yes

- name: Install dotfiles
  command: "rcup -d {{ dotfiles_dest }}"
  when: dotfiles.installation == 'true'
  become: yes
  become_user: "{{ user.name }}"
