---

- name: Setup ArchLinux/Debian system
  hosts: localhost
  connection: local
  become: True

  roles:
    - role: base
      tags: [ base ]
    - role: userinterface
      tags: [ ui ]
    - role: dotfiles
      tags: [ base, dotfiles ]
